#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Denodo Platform Documentation documentation build configuration file, created by
# sphinx-quickstart on Wed Apr 13 20:09:19 2016.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os
import datetime
import sphinx_rtd_theme

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.insert(0, os.path.abspath('.'))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    # 'sphinx.ext.autodoc',
    # 'sphinx.ext.doctest',
    
    # This extension can generate automatic links to the documentation of objects in other projects.
    # 'sphinx.ext.intersphinx',
    
    # Support for todo items
    # 'sphinx.ext.todo',
     
    # 'sphinx.ext.coverage',
    # 'sphinx.ext.imgmath',
    'sphinx.ext.ifconfig',
    
    # Allow reference sections using its title (http://www.sphinx-doc.org/es/stable/ext/autosectionlabel.html)
	'sphinx.ext.autosectionlabel',
	
	#'sphinxprettysearchresults'
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The encoding of source files.
source_encoding = 'utf-8'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'Denodo Platform'
copyright = '{0}, Denodo Technologies'.format(datetime.date.today().year)

#u'2008-{0}'.format(datetime.date.today().year)
author = 'Denodo Technologies'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '7.0'
# The full version, including alpha/beta/rc tags.
release = '7.0 GA'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The reST default role (used for this markup: `text`) to use for all
# documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
show_authors = True

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
#keep_warnings = False

# If true, `todo` and `todoList` produce output, else they produce nothing.
# todo_include_todos = True

# If true, Sphinx will warn about all references where the target cannot be found
nitpicky = True


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#html_theme = 'alabaster'
# html_theme = 'classic'
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
	#'textcolor': 'rgb(73, 71, 71)'
	#, 'externalrefs': 'true'
	#, 'bodyfont': '"Lucida Grande",Arial,sans-serif'
	#, 'headfont': '"Lucida Grande",Arial,sans-serif'
	#, 'headtextcolor': 'rgb(49, 48, 48)'
	#, 'footerbgcolor':  'rgb(255, 255, 255)'
	#, 'footertextcolor': 'rgb(73, 71, 71)'
	#, 'sidebarbgcolor': 'rgb(235, 235, 237)'
    #, 'sidebarlinkcolor': 'rgb(51, 51, 51)'
	#, 'sidebartextcolor': 'rgb(51, 51, 51)'
	##, 'relbarbgcolor': 'rgb(255,51,51)'
	#, 'relbarbgcolor': 'rgb(255,255,255)'
	#, 'relbartextcolor': 'rgb(73, 71, 71)'
	#, 'relbarlinkcolor': 'rgb(73, 71, 71)'
	"collapse_navigation" : False,
	"sticky_navigation": True
}

    
#   footerbgcolor (CSS color): Background color for the footer line.
#    footertextcolor (CSS color): Text color for the footer line.
#    sidebarbgcolor (CSS color): Background color for the sidebar.
#    sidebarbtncolor (CSS color): Background color for the sidebar collapse button (used when collapsiblesidebar is True).
#    sidebartextcolor (CSS color): Text color for the sidebar.
#    sidebarlinkcolor (CSS color): Link color for the sidebar.
#    relbarbgcolor (CSS color): Background color for the relation bar.
#    relbartextcolor (CSS color): Text color for the relation bar.
#    relbarlinkcolor (CSS color): Link color for the relation bar.
#    bgcolor (CSS color): Body background color.
#    textcolor (CSS color): Body text color.
#    linkcolor (CSS color): Body link color.
#    visitedlinkcolor (CSS color): Body color for visited links.
#    headbgcolor (CSS color): Background color for headings.
#    headtextcolor (CSS color): Text color for headings.
#    headlinkcolor (CSS color): Link color for headings.
#    codebgcolor (CSS color): Background color for code blocks.
#    codetextcolor (CSS color): Default text color for code blocks, if not set differently by the highlighting style.
#    bodyfont (CSS font-family): Font for normal text.
#    headfont (CSS font-family): Font for headings.




# Add any paths that contain custom themes here, relative to this directory.
#html_theme_path = []

# The name for this set of Sphinx documents.
# "<project> v<release> documentation" by default.
html_title = 'Denodo Platform Online Documentation 7.0 BETA 2'

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = '_static/images/logo.png'

# The name of an image file (relative to this directory) to use as a favicon of
# the docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = '_static/images/favicon.ico'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_context = {
    'css_files': [
        '_static/theme_overrides.css',  # overrides for wide tables in RTD theme
        ],
    }

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
#html_extra_path = []

# If not None, a 'Last updated on:' timestamp is inserted at every page
# bottom, using the given strftime format.
# The empty string is equivalent to '%b %d, %Y'.

# csantos@2016/10/13: we do not want to add this footer because it would 
# appear in all the pages of all the versions even if we only change 
# something on one of the versions.
html_last_updated_fmt = None

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
# html_use_smartypants = True
# csantos@2018/03/20: in Sphinx 1.6.X, html_use_smartypants is deprecated. We must use this property instead.
smartquotes = True


# Custom sidebar templates, maps document names to template names.
# html_sidebars = {
#     'index': 'indexsidebar.html',
# }

# Additional templates that should be rendered to pages, maps page names to
# template names.
# html_additional_pages = {
#     'index': 'indexcontent.html',
# }

# If false, no module index is generated.
html_domain_indices = True

# If false, no index is generated.
html_use_index = True

# If true, the index is split into individual pages for each letter.
html_split_index = False

# If true, the reST sources are included in the HTML build as _sources/name. The default is True.
#
# csantos@2019/01/22: Set to false to avoid an extra step in the build, a step that is unnecessary.
html_copy_source = False

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = False

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sphinx = False

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
html_show_copyright = False

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
# html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'h', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'r', 'sv', 'tr', 'zh'
html_search_language = 'en'

# A dictionary with options for the search language support, empty by default.
# 'ja' uses this config value.
# 'zh' user can custom change `jieba` dictionary path.
#html_search_options = {'type': 'default'}

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
#html_search_scorer = 'scorer.js'

# Output file base name for HTML help builder.
htmlhelp_basename = 'DenodoPlatformDocumentationdoc'

# Encoding of HTML output files
html_output_encoding = 'utf-8'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
 #The paper size ('letterpaper' or 'a4paper').
 'papersize': 'letterpaper',

# The font size ('10pt', '11pt' or '12pt').
 'pointsize': '12pt',

# Additional stuff for the LaTeX preamble.
 'preamble': '',

# Latex figure (float) alignment
 'figure_align': 'htbp'
}

latex_paper_size = 'letterpaper'

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    ('aracne/administration/index', 'Aracne_Administration_Guide.tex', 'Aracne Administration Guide', 
     'Denodo Technologies', 'manual'),
    ('itpilot/developer/index', 'ITPilot_Developer_Guide.tex', 'ITPilot Developer Guide', 
     'Denodo Technologies', 'manual'),
    ('itpilot/dextl/index', 'ITPilot_DEXTL_Guide.tex', 'ITPilot DEXTL Guide', 
     'Denodo Technologies', 'manual'),
    ('itpilot/generation_environment/index', 'ITPilot_Generation_Environment_Guide.tex', 'ITPilot Generation Environment Guide', 
     'Denodo Technologies', 'manual'),
    ('itpilot/nseql/index', 'ITPilot_NSEQL_Guide.tex', 'ITPilot NSEQL Guide', 
     'Denodo Technologies', 'manual'),
    ('itpilot/user_guide/index', 'ITPilot_User_Guide.tex', 'ITPilot User Guide', 
     'Denodo Technologies', 'manual'),
    ('platform/installation/index', 'Denodo_Platform_Installation_Guide.tex', 'Denodo Platform Installation Guide', 
     'Denodo Technologies', 'manual'),
    ('platform/migration/index', 'Denodo_Platform_Migration_Guide.tex', 'Denodo Platform Migration Guide', 
     'Denodo Technologies', 'manual'),
    ('platform/new_features/index', 'Denodo_Platform_New_Features_Guide.tex', 'Denodo Platform New Features Guide', 
     'Denodo Technologies', 'manual'),
    ('scheduler/administration/index', 'Scheduler_Administration_Guide.tex', 'Scheduler Administration Guide', 
     'Denodo Technologies', 'manual'),
    ('vdp/administration/index', 'Virtual_DataPort_Administration_Guide.tex', 'Virtual DataPort Administration Guide', 
     'Denodo Technologies', 'manual'),
    ('vdp/developer/index', 'Virtual_DataPort_Developer_Guide.tex', 'Virtual DataPort Developer Guide',
     'Denodo Technologies', 'manual'),
    ('vdp/dmt/index', 'Virtual_DataPort_Developer_Diagnostic_Monitoring_Tool_Guide.tex', 'Virtual DataPort Diagnostic & Monitoring Tool Guide',
     'Denodo Technologies', 'manual'),
    ('vdp/data_catalog/index', 'Virtual_DataPort_Information_Self-Service_Tool_Guide.tex', 'Data Catalog Guide',
     'Denodo Technologies', 'manual'),
    ('vdp/vql/index', 'Virtual_DataPort_DataPort_VQL_Guide.tex', 'Virtual DataPort VQL Guide',
     'Denodo Technologies', 'manual'),
    ('solution_manager/administration/index', 'Solution_Manager_Administration_Guide.tex', 'Solution Manager Administration Guide',
     'Denodo Technologies', 'manual')

]

#latex_toplevel_sectioning = 'section'

latex_engine = 'xelatex'

latex_elements = {
  'classoptions': ',openany,oneside'
}

# The name of an image file (relative to this directory) to place at the top of
# the title page.
latex_logo = '_static/images/logo_denodo_pdf_header.png'

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False

# If true, show page references after internal links.
#latex_show_pagerefs = False

# If true, show URL addresses after external links.
latex_show_urls = 'False'

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
# latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'denodoplatformdocumentation', 'Denodo Platform Documentation Documentation',
     [author], 1)
]

# If true, show URL addresses after external links.
#man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'DenodoPlatformDocumentation', 'Denodo Platform Documentation Documentation',
     author, 'DenodoPlatformDocumentation', 'One line description of project.',
     'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
#texinfo_appendices = []

# If false, no module index is generated.
#texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
#texinfo_no_detailmenu = False


# -- Options for Epub output ----------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project
epub_author = author
epub_publisher = author
epub_copyright = copyright

# The basename for the epub file. It defaults to the project name.
#epub_basename = project

# The HTML theme for the epub output. Since the default themes are not
# optimized for small screen space, using the same theme for HTML and epub
# output is usually not wise. This defaults to 'epub', a theme designed to save
# visual space.
#epub_theme = 'epub'

# The language of the text. It defaults to the language option
# or 'en' if the language is not set.
#epub_language = ''

# The scheme of the identifier. Typical schemes are ISBN or URL.
#epub_scheme = ''

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#epub_identifier = ''

# A unique identification for the text.
#epub_uid = ''

# A tuple containing the cover image and cover page html template filenames.
#epub_cover = ()

# A sequence of (type, uri, title) tuples for the guide element of content.opf.
#epub_guide = ()

# HTML files that should be inserted before the pages created by sphinx.
# The format is a list of tuples containing the path and title.
#epub_pre_files = []

# HTML files that should be inserted after the pages created by sphinx.
# The format is a list of tuples containing the path and title.
#epub_post_files = []

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']

# The depth of the table of contents in toc.ncx.
#epub_tocdepth = 3

# Allow duplicate toc entries.
#epub_tocdup = True

# Choose between 'default' and 'includehidden'.
#epub_tocscope = 'default'

# Fix unsupported image types using the Pillow.
#epub_fix_images = False

# Scale large images.
#epub_max_image_width = 0

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#epub_show_urls = 'inline'

# If false, no index is generated.
#epub_use_index = True


# Example configuration for intersphinx: refer to the Python standard library.
#intersphinx_mapping = {'https://docs.python.org/': None}
# intersphinx_mapping = {'vdp_admin': ('https://community.denodo.com/docs/html/browse/6.0/vdp/administration/index',
#                                  './../vdp/administration/index.txt'),
#                       'vql_guide': ('https://community.denodo.com/docs/html/browse/6.0/vdp/vql/index',
#                                  './../vdp/vql/index.txt')}

# numfig = 'true'

highlight_language = 'sql'

# numfig_format = {'figure': 'Figure %s',

# numfig_format = {'figure': 'Figure',
#                  'table': 'Table',
#                  'code-block': 'Listing'}

# Ignore URLs to localhost when running "make linkhtml"
linkcheck_ignore = [r'(http://localhost:\d+/|https://localhost:\d+/|http://acme:\d+/|http://localhost/|https://localhost/)']
linkcheck_retries = 3

exec(open("./vql_lexer.py").read())